### ISSUE TITLE
It compiles fine, however safemode-ui-hook.dylib can't be found

### ISSUE THREAD

**Issue by isklikas** [comex/substitute#10]
And as a result, a deb can't be made...

![screen shot 2015-07-16 at 5 41 38 pm](https://cloud.githubusercontent.com/assets/3051658/8726291/fd24d8d4-2be1-11e5-9ad1-009e08e2de0f.png)

**Comment by comex** [comment]
Sorry, I need to update the readme.

Please configure with `--xcode-sdk=iphoneos --enable-ios-bootstrap`.  Currently you are compiling a Mac version.
