### ISSUE TITLE
Substitute not loading

### ISSUE THREAD

**Issue by haniag** [comex/substitute#23]
I installed Substitute, but I am unable to load daemon as when I run 

`launchctl load /Library/LaunchDaemons/com.ex.substituted.plist`

I get this error 

`/Library/LaunchDaemons/com.ex.substituted.plist: Requestor is not a platform binary`

I checked permissions, and all is root:wheel. Also, I did reboot phone after installing. Note that I don't have DPKG, and installed Substitute by manually copying its deb files, and setting permissions accordingly. I am on iPhone9,3 11.1

**Comment by comex** [comment]
Unfortunately, this software has not been updated for recent versions of iOS or recent jailbreaks, so I wouldn't expect it to do anything useful even if you could get it to run.

**Comment by haniag** [comment]
Thanks
