### ISSUE TITLE
may I ask why use xxpc.h instead of xpc.h ?

### ISSUE THREAD

**Issue by roothide** [comex/substitute#33]
may I ask why use xxpc.h instead of xpc.h ?

**Comment by comex** [comment]
Because libxpc is considered a private API on iOS and so headers are not provided in the SDK.

(That was the reason when this was originally developed.  While I am not maintaining Substitute today, the situation doesn't seem to have changed since.)

**Comment by roothide** [comment]
Thank you for your reply.
I was just curious why the xxpc prefix was used instead of the xpc prefix, I thought you had a custom xpc module, haha.
so it seems that just because it is a private header file.
