### ISSUE TITLE
is iOS supported already? (both 32 and 64 bits?) <EOM>

### ISSUE THREAD

**Issue by mkravchik** [comex/substitute#8]

**Comment by alexzielenski** [comment]
For function hooking. But bootstrap and safe mode are still in the works.

**Comment by mkravchik** [comment]
Can I link with it statically?

Date: Sun, 29 Mar 2015 08:00:36 -0700

**Comment by comex** [comment]
Belatedly, yes, but at the moment I suggest copying the relevant .c files into your project, since you won't need most of it.  This will be improved.
